---

- name: configure servers
  hosts : all
  become: true
  tasks:
    - name: update servers
      yum: update_cache=yes

    - name: Install httpd
      yum: name=httpd update_cache=yes state=latest

    - name: Set Timezone to Africa/lagos
      timezone: name=Africa/Lagos

    - name: Print hostname on my servers
      shell: echo "<h1 style="background-color:pink">Welcome to PRAESTO HEALTH TEST PAGE, This is my IP $(hostname -f)</h1>" > /var/www/html/index.html

    - name: Restart httpd
      service: name=httpd state=restarted enabled=yes